name: Lint & test
on: [push]
jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build docker
        run: docker-compose build
      - name: Run isort
        run: docker-compose run django isort src/ --check
      - name: Run black
        run: docker-compose run django black src/ --check
      - name: Run flake8
        run: docker-compose run django flake8
      - name: Run mypy
        run: docker-compose run django mypy --config mypy.ini src/
      - name: Run tests
        run: docker-compose run django py.test

#  deploy_to_heroku:
#    runs-on: ubuntu-latest
#    needs: build
#    if: github.ref == 'refs/heads/master'
#    steps:
#      - uses: actions/checkout@v3
#        with:
#          fetch-depth: "0"
#      - name: Deploy to Heroku
#        env:
#          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
#          HEROKU_APP_NAME: "hacksoft-styleguide-example"
#        run: git push --force https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git origin/master:master
